In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("PyTorch version:", torch.__version__)
print("Using GPU:", torch.backends.mps.is_available() if torch.backends.mps.is_available() else "No GPU")

PyTorch version: 2.7.1
Using GPU: True


In [3]:
import torch
print("CUDA available:", torch.cuda.is_available())   # will be False
print("MPS available :", torch.backends.mps.is_available())
x = torch.randn(1000,1000, device="mps")              # runs on Apple GPU

print(x.mean())

CUDA available: False
MPS available : True
tensor(0.0002, device='mps:0')


## Tensors

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()
#Get tesnor bacl as python int

7

In [7]:
#vector
vector = torch.tensor([7,7])

In [8]:
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim
MATRIX[1]
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor()

## Random Tensors
its the way NN learn is that they start with tensors full of random numbers and then adjust those random numbers to bettwe represent the data

In [19]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3285, 0.6171, 0.0108, 0.9145],
         [0.1910, 0.2074, 0.9460, 0.5330],
         [0.1008, 0.3340, 0.0964, 0.7642]]])

In [20]:
random_tensor.ndim

3

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #H,W,color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
### Zeros and one

In [24]:
zeros = torch.zeros(3,4)

In [26]:
ones = torch.ones(3,4)

## Tensor datatypes

In [4]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=float, device ="cpu", requires_grad=False )

In [5]:
float_32_tensor.dtype

torch.float64

In [6]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [7]:
float_16_tensor.dtype

torch.float16

In [8]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

## Geeting info from tensor
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not right device

In [9]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2165, 0.4991, 0.9121, 0.7154],
        [0.4962, 0.1363, 0.8952, 0.2088],
        [0.2183, 0.8548, 0.6766, 0.9148]])

In [10]:
some_tensor.dtype

torch.float32

In [11]:
some_tensor.shape

torch.Size([3, 4])

In [12]:
some_tensor.size()

torch.Size([3, 4])

In [13]:
some_tensor.device

device(type='cpu')

## Manipulating Tensors (tensor operations)

Include addition, sub, multiplicatoion (element - wise) division and matrix multiplication

In [14]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [15]:
tensor * 10

tensor([10, 20, 30])

In [16]:
tensor - 10

tensor([-9, -8, -7])

In [18]:
tensor.mul( 10)

tensor([10, 20, 30])