In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("PyTorch version:", torch.__version__)
print("Using GPU:", torch.backends.mps.is_available() if torch.backends.mps.is_available() else "No GPU")

PyTorch version: 2.7.1
Using GPU: True


In [2]:
import torch
print("CUDA available:", torch.cuda.is_available())   # will be False
print("MPS available :", torch.backends.mps.is_available())
x = torch.randn(1000,1000, device="mps")              # runs on Apple GPU

print(x.mean())

CUDA available: False
MPS available : True
tensor(-0.0002, device='mps:0')


## Tensors

A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions.
In simple terms: it’s a multi-dimensional array of numbers.

In [ ]:
#scalar is a single number tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()
#Get tesnor bacl as python int

7

In [ ]:
#vector is a 1 dimensional tensor
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX 
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim
MATRIX[1]
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor()

## Random Tensors
its the way NN learn is that they start with tensors full of random numbers and then adjust those random numbers to bettwe represent the data

In [19]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3285, 0.6171, 0.0108, 0.9145],
         [0.1910, 0.2074, 0.9460, 0.5330],
         [0.1008, 0.3340, 0.0964, 0.7642]]])

In [20]:
random_tensor.ndim

3

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #H,W,color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
### Zeros and one

In [24]:
zeros = torch.zeros(3,4)

In [26]:
ones = torch.ones(3,4)

## Tensor datatypes

In [4]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=float, device ="cpu", requires_grad=False )

In [5]:
float_32_tensor.dtype

torch.float64

In [6]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [7]:
float_16_tensor.dtype

torch.float16

In [8]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

## Geeting info from tensor
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not right device

In [9]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2165, 0.4991, 0.9121, 0.7154],
        [0.4962, 0.1363, 0.8952, 0.2088],
        [0.2183, 0.8548, 0.6766, 0.9148]])

In [10]:
some_tensor.dtype

torch.float32

In [11]:
some_tensor.shape

torch.Size([3, 4])

In [12]:
some_tensor.size()

torch.Size([3, 4])

In [13]:
some_tensor.device

device(type='cpu')

## Manipulating Tensors (tensor operations)

Include addition, sub, multiplicatoion (element - wise) division and matrix multiplication

In [14]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [15]:
tensor * 10

tensor([10, 20, 30])

In [16]:
tensor - 10

tensor([-9, -8, -7])

In [18]:
tensor.mul( 10)

tensor([10, 20, 30])

## Finding the min, max, sum etc tensor aggreation

In [12]:
# create a tensor
x = torch.arange(0,100,10)
x
x.dtype

torch.int64

In [13]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [14]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [15]:
## Mean cant take int 64 dtype so need to convert dtype to calcualte mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [16]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [19]:
# Argmax and argmin
# find positioon in tensor that has min or max value that returns index postion of target tensor where min or max value is located
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [20]:
torch.argmin(x), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stakcing, squeezing and unsqueezing tensors
### Reshaping: respahes input tensor to a defined tensor
### View - Returen a view of an input tensor of certain shape but keep the same memory as the original tensor
### Stacking - combine multile tensors on top of each other (vtsack) or side by side (hstack)
### Squeeze - remove all  '1' from dimension from a tensor (single dimensions)
### Unsqueeze - add a  1 to a target ttensor 
### Permute: Retuern a view of the input with dimenesios permuted(swapped) in a certain way

In [22]:
x = torch.arange(1. ,10.) # . makes it a float tensor
x.shape, x

(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [24]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape
# compantiable beacise 1* 9 is 9



(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [30]:
# if we change to 
y = torch.arange(1., 13.)
y_reshaped = y.reshape(3,4)

y, y.shape, y_reshaped, y_reshaped.shape

y = torch.arange(1., 15.)   # 14 elements
y.reshape(3, 4)             # needs 12

RuntimeError: shape '[3, 4]' is invalid for input of size 14

In [31]:
# Chnage the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [33]:
# Changing z chanes x (beacuse they share the same memory as the original tensor)
z[:,0] = 5 # synatax: 	•	: → all rows
                    # 	•	0 → first column

z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [37]:
# stack 
x_stacked = torch.stack([x,x,x,x], dim = 1)
'''
dim=0 → stack vertically

Like rows added.

dim=1 → stack horizontally

'''
x_stacked, x_stacked.shape


(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [38]:
# squeeze removes all single dimensions from a target tensor
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [39]:
x_reshaped.shape

torch.Size([9, 1])

In [45]:
x_squeeze = x_reshaped.squeeze() # changed dim from [[]] to []

In [44]:
 x_reshaped.squeeze().shape

torch.Size([9])

In [49]:
# unsqueuze adds a single dimension to a target tensor at a specified dim

print(f"previous target: {x_squeeze} and shape is {x_squeeze.shape}")
print(f"unsqueezed at dim 0: {x_squeeze.unsqueeze(dim=0)} and shape is {x_squeeze.unsqueeze(dim=0).shape}")
print(f"unsqueezed at dim 1: {x_squeeze.unsqueeze(dim=1)} and shape is {x_squeeze.unsqueeze(dim=0).shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) and shape is torch.Size([9])
unsqueezed at dim 0: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) and shape is torch.Size([1, 9])
unsqueezed at dim 1: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) and shape is torch.Size([1, 9])


In [50]:
# permuste: rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #H,W,color channels (R,G,B)
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 2, 1 to 0, 2 to 1
x_original.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [52]:
x_original[0,0,0] = 46748738
x_permuted = x_original.permute(2, 0, 1)
x_permuted[0,0,0]

tensor(46748736.)